<?php
declare(strict_types=1);

/**
 * Backend Form Configuration - Example Template
 *
 * Copy this file to forms-config.php and customize for your deployment.
 * The forms-config.php file is gitignored — safe for server-specific settings.
 *
 * USAGE:
 * ------
 * 1. Copy this file: cp forms-config.example.php forms-config.php
 * 2. Edit forms-config.php with your site-specific values
 *
 * MULTI-SERVER SETUP:
 * -------------------
 * Frontend and Backend run on separate servers. Each server maintains its own
 * forms-config.php. The form keys (e.g. 'bs', 'bk') must match between servers.
 *
 * The backend primarily uses the 'pdf' section of each form's config.
 * Other fields (form, theme, notify_email) are used by the frontend only,
 * but are kept here for consistency.
 */

return [

    // =========================================================================
    // Example form: Berufsschule (bs)
    // =========================================================================
    'bs' => [
        'db' => true,
        'form'  => 'bs.json',         // Frontend only
        'theme' => 'survey_theme.json', // Frontend only
        'version' => '2026-01-v2',
        'notify_email' => 'sekretariat@example.com', // Frontend only

        // PDF Download Configuration
        // PDF is generated by the backend on demand after a successful submission.
        'pdf' => [
            'enabled' => true,
            'required' => false,        // If true, frontend blocks progress until PDF is downloaded
            'title' => 'Anmeldebestätigung',
            'download_title' => 'Bestätigung als PDF herunterladen',
            'token_lifetime' => 1800,   // seconds; must match frontend config

            // Logo (optional)
            // Use an absolute path on the backend server, or null to disable.
            'logo' => null,             // e.g., '/var/www/html/templates/pdf/logo.png'

            // PDF content
            'header_title' => 'Anmeldebestätigung',
            'intro_text' => 'Vielen Dank für Ihre Anmeldung. Diese Bestätigung dient als Nachweis.',
            'footer_text' => 'Bei Fragen wenden Sie sich bitte an unser Sekretariat.',

            // Field filtering
            'include_fields' => 'all',
            'exclude_fields' => ['consent_datenschutz', 'consent_agb'],

            // Custom sections (optional)
            'pre_sections' => [],
            'post_sections' => [],
        ],
    ],

    // =========================================================================
    // Example form: Berufskolleg (bk)
    // =========================================================================
    'bk' => [
        'db' => true,
        'form'  => 'bk.json',
        'theme' => 'survey_theme.json',
        'version' => '2026-01-v2',
        'notify_email' => '',

        'pdf' => [
            'enabled' => true,
            'required' => false,
            'title' => 'Anmeldebestätigung',
            'download_title' => 'Bestätigung als PDF herunterladen',
            'token_lifetime' => 1800,

            'logo' => null,
            'header_title' => 'Anmeldebestätigung Berufskolleg',
            'intro_text' => 'Vielen Dank für Ihre Anmeldung am Berufskolleg.',
            'footer_text' => 'Bei Fragen kontaktieren Sie uns bitte.',

            'include_fields' => 'all',
            'exclude_fields' => ['consent_datenschutz'],

            'pre_sections' => [],
            'post_sections' => [],
        ],
    ],

    // =========================================================================
    // Example form without PDF
    // =========================================================================
    // 'ausbildernachmittag' => [
    //     'db' => false,
    //     'form'  => 'ausbildernachmittag.json',
    //     'theme' => 'survey_theme.json',
    //     'version' => '2026-01-v2',
    //     'notify_email' => 'ausbildernachmittag@example.com',
    //     // No 'pdf' key = PDF disabled
    // ],

];
