services:
  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - ..:/var/www:ro
      - .:/var/www/backend
      - vendor-cache:/var/www/backend/vendor
    working_dir: /var/www/backend
    command: composer test

  coverage:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    volumes:
      - ..:/var/www:ro
      - .:/var/www/backend
      - vendor-cache:/var/www/backend/vendor
    working_dir: /var/www/backend
    command: composer test:coverage

volumes:
  vendor-cache:
