#!/bin/bash
set -e

echo "🚀 Starting Backend Entrypoint..."

# MySQL healthcheck is handled by docker-compose
# Skip manual wait as depends_on already ensures MySQL is healthy
echo "⏳ MySQL should be ready (checked by docker-compose healthcheck)"

# The backend reads its settings from .env (EnvLoader), and values in that file win over the
# container environment. In Docker the file is therefore GENERATED from the container
# environment (root .env -> docker-compose) on every start, so changes there take effect after
# a restart. Generated files carry GENERATED_MARKER in the first line.
#
# A file WITHOUT the marker was written by hand (e.g. copied from .env.example) and is never touched.
# Remove the marker line to take over a generated file. Files generated by older versions (first line
# "# Application", no marker) are recognised, saved as .env.bak and regenerated once. Settings the
# entrypoint does not manage are carried over (see regenerate_env_file).
GENERATED_MARKER="# GENERATED-BY-ENTRYPOINT"

write_env_file() {
    cat > "$1" <<EOF
${GENERATED_MARKER} - regenerated from the container environment on every start. Remove this line to edit by hand.
# Application
APP_ENV=${APP_ENV:-production}
APP_DEBUG=${APP_DEBUG:-false}

# Database
DB_HOST=${DB_HOST:-mysql}
DB_PORT=${DB_PORT:-3306}
DB_NAME=${DB_NAME:-anmeldung}
DB_USER=${DB_USER:-anmeldung}
DB_PASS=${DB_PASS:-secret}

# Auto-Expunge
AUTO_EXPUNGE_DAYS=${AUTO_EXPUNGE_DAYS:-90}
AUTO_MARK_AS_READ=${AUTO_MARK_AS_READ:-true}

# Session
SESSION_LIFETIME=${SESSION_LIFETIME:-3600}
SESSION_SECURE=${SESSION_SECURE:-false}

# Authentication (Optional)
AUTH_ENABLED=${AUTH_ENABLED:-false}

# PDF Tokens
PDF_TOKEN_SECRET=${PDF_TOKEN_SECRET:-change-me-min-32-characters}

# API Secret
API_SECRET_KEY=${API_SECRET_KEY:-dev-api-key-replace-in-production}

# Multi-Tenant Mode
MULTI_TENANT_ENABLED=${MULTI_TENANT_ENABLED:-false}

# Reverse proxies whose X-Forwarded-For is trusted (comma-separated IPs/CIDR; empty = ignore the header)
TRUSTED_PROXIES=${TRUSTED_PROXIES:-}

# Platform Admin (required for multi-tenant mode)
ADMIN_USERNAME=${ADMIN_USERNAME:-}
ADMIN_PASSWORD_HASH=${ADMIN_PASSWORD_HASH:-}

# File Upload
UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:-10485760}
UPLOAD_ALLOWED_TYPES=${UPLOAD_ALLOWED_TYPES:-pdf,jpg,jpeg,png,gif,doc,docx}
EOF
}

# Keep settings the entrypoint does not manage (e.g. PDF_LOGO_PATH, RATE_LIMIT_*, VIRUS_SCAN_*) when a
# generated file is rewritten: every KEY=VALUE line of the old file whose key is not in the new one
# is appended. Keys the entrypoint manages always come from the container environment.
regenerate_env_file() {
    write_env_file .env.new
    local extras
    extras=$(grep -E '^[A-Za-z_][A-Za-z0-9_]*=' .env | while IFS= read -r line; do
        key="${line%%=*}"
        grep -q "^${key}=" .env.new || printf '%s\n' "$line"
    done)
    if [ -n "$extras" ]; then
        printf '\n# Custom settings preserved from the previous .env\n%s\n' "$extras" >> .env.new
    fi
    mv .env.new .env
}

if [ ! -f .env ]; then
    echo "📝 Creating .env file..."
    write_env_file .env
    echo "✅ .env file created!"
elif head -n 1 .env | grep -q "^${GENERATED_MARKER}"; then
    echo "📝 Regenerating generated .env from the container environment..."
    regenerate_env_file
elif [ "$(head -n 1 .env)" = "# Application" ]; then
    echo "📝 Replacing .env generated by an older version (backup: .env.bak)..."
    cp .env .env.bak
    regenerate_env_file
else
    echo "ℹ️  Using hand-written .env (no generated marker) — container environment changes do not apply to it."
fi

# Warn about a mangled ADMIN_PASSWORD_HASH (the usual cause: an unquoted value in the root .env, where
# Docker Compose expands the "$..." parts). A valid bcrypt/argon2 hash looks like $2y$10$<53 chars>.
if [ -n "${ADMIN_PASSWORD_HASH:-}" ] \
   && ! printf '%s' "$ADMIN_PASSWORD_HASH" | grep -Eq '^\$2[abxy]\$[0-9]{2}\$[./A-Za-z0-9]{53}$|^\$argon2(id|i|d)\$'; then
    echo "⚠️  ADMIN_PASSWORD_HASH looks damaged (length ${#ADMIN_PASSWORD_HASH}, a bcrypt hash has 60)."
    echo "    Wrap it in single quotes in the root .env: ADMIN_PASSWORD_HASH='\$2y\$10\$...'"
    echo "    then run: docker compose up -d backend"
fi

# Install/update Composer dependencies
if [ ! -d "vendor" ] || [ ! -f "vendor/autoload.php" ]; then
    echo "📦 Installing Composer dependencies..."
    composer install --no-interaction --prefer-dist --optimize-autoloader
    echo "✅ Composer dependencies installed!"
fi

# Run database migration (idempotent — safe to run on every start)
# The v3 schema (tenants, form_configs, anmeldungen.tenant_id) is required in BOTH
# single- and multi-tenant mode: all repositories read and write tenant_id. Upgrades
# from v2.x therefore must migrate regardless of MULTI_TENANT_ENABLED.
# Must run after composer install so vendor/autoload.php is available.
echo "🏢 Running database migration..."
php /var/www/html/migrate.php
echo "✅ Migration complete!"

# Create required directories
echo "📁 Creating required directories..."
mkdir -p uploads cache logs
echo "✅ Directories created!"

# Set permissions (only for writable directories, not entire volume)
echo "🔐 Setting permissions..."
chown -R www-data:www-data uploads cache logs
chmod -R 755 uploads cache logs
echo "✅ Permissions set!"

echo "✅ Backend setup complete!"
echo "🌐 Backend available at: http://localhost:9080"
echo "📊 Admin interface: http://localhost:9080/index.php"
echo ""

# Execute CMD (apache2-foreground)
exec "$@"
